import type { BlogCategory, BlogAuthor, BlogPost, BlogBlock } from './types';

export const MOCK_BLOG_CATEGORIES: BlogCategory[] = [
  { id: 'cat-renting', slug: 'renting', name: 'Renting', icon: 'home', position: 0, description: 'Tips and guides for finding your next rental.' },
  { id: 'cat-moving', slug: 'moving', name: 'Moving', icon: 'car', position: 1, description: 'Everything you need to know about relocating.' },
  { id: 'cat-home-decor', slug: 'home-decor', name: 'Home Decor', icon: 'color-palette', position: 2, description: 'Ideas and inspiration for decorating your home.' },
  { id: 'cat-neighbourhoods', slug: 'neighbourhoods', name: 'Neighbourhoods', icon: 'map', position: 3, description: 'In-depth guides to Nairobi\'s best estates.' },
  { id: 'cat-landlord-advice', slug: 'landlord-advice', name: 'Landlord Advice', icon: 'people', position: 4, description: 'Best practices for managing rental properties.' },
  { id: 'cat-finance', slug: 'finance', name: 'Finance', icon: 'cash', position: 5, description: 'Budgeting, saving, and financial planning for housing.' },
  { id: 'cat-marketplace', slug: 'marketplace', name: 'Marketplace', icon: 'cart', position: 6, description: 'Buy and sell home essentials.' },
  { id: 'cat-hama-news', slug: 'hama-news', name: 'HAMA News', icon: 'megaphone', position: 7, description: 'Latest updates and announcements from HAMA.' },
  { id: 'cat-success-stories', slug: 'success-stories', name: 'Success Stories', icon: 'trophy', position: 8, description: 'Real stories from real HAMA users.' },
  { id: 'cat-security', slug: 'security', name: 'Security', icon: 'shield-checkmark', position: 9, description: 'Keeping your home and family safe.' },
  { id: 'cat-utilities', slug: 'utilities', name: 'Utilities', icon: 'flash', position: 10, description: 'Managing water, electricity, and internet.' },
  { id: 'cat-interior-design', slug: 'interior-design', name: 'Interior Design', icon: 'brush', position: 11, description: 'Professional design tips for every budget.' },
  { id: 'cat-property-investment', slug: 'property-investment', name: 'Property Investment', icon: 'trending-up', position: 12, description: 'Grow your wealth through real estate.' },
  { id: 'cat-tenant-advice', slug: 'tenant-advice', name: 'Tenant Advice', icon: 'person', position: 13, description: 'Know your rights and responsibilities as a tenant.' },
  { id: 'cat-buying', slug: 'buying', name: 'Buying', icon: 'key', position: 14, description: 'Guides for purchasing your first or next home.' },
];

export const MOCK_BLOG_AUTHORS: BlogAuthor[] = [
  {
    id: 'author-editorial',
    slug: 'hama-editorial',
    name: 'HAMA Editorial',
    avatarUrl: '/avatars/hama-editorial.jpg',
    bio: 'The HAMA content team brings you expert advice, market insights, and practical tips to help you navigate the Kenyan housing market with confidence.',
  },
  {
    id: 'author-wanjiku',
    slug: 'wanjiku-mwangi',
    name: 'Wanjiku Mwangi',
    avatarUrl: '/avatars/wanjiku-mwangi.jpg',
    bio: 'Wanjiku is a Nairobi-based housing writer with over eight years of experience covering the Kenyan real estate market. She helps renters and homeowners make smarter decisions.',
  },
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: 'post-1',
    slug: 'how-to-find-affordable-rentals-in-nairobi',
    title: 'How to Find Affordable Rentals in Nairobi',
    excerpt: 'Finding an affordable rental in Nairobi doesn\'t have to be a nightmare. Here\'s your step-by-step guide to scoring a great deal.',
    content: [
      { type: 'heading', level: 2, text: 'Understanding the Nairobi Rental Market' },
      { type: 'paragraph', text: 'Nairobi\'s rental market is as diverse as the city itself. From the bustling streets of Pipeline to the quiet lanes of Donholm, prices vary wildly.' },
      { type: 'callout', tone: 'tip', text: 'Always calculate your total monthly cost before signing a lease. Add rent plus water, electricity, service charge, internet, and garbage collection.' },
      { type: 'heading', level: 2, text: 'Where to Start Your Search' },
      { type: 'list', ordered: false, items: [
        'Use the HAMA app to filter by price, location, and amenities.',
        'Visit estates in person at different times of day.',
        'Talk to current tenants about their experience.',
        'Negotiate your rent by offering a longer lease.',
      ] },
    ],
    coverImageUrl: 'hood-2-nairobi-skyline.jpg',
    category: MOCK_BLOG_CATEGORIES[0],
    author: MOCK_BLOG_AUTHORS[1],
    tags: ['renting', 'nairobi', 'affordable housing'],
    status: 'published',
    publishedAt: '2026-08-10T08:00:00Z',
    featured: true,
    pinned: false,
    views: 3420,
    shares: 187,
    readingTime: 8,
    seoTitle: 'How to Find Affordable Rentals in Nairobi | HAMA',
    seoDescription: 'Discover practical tips for finding affordable rental apartments in Nairobi.',
  },

  {
    id: 'post-2',
    slug: 'how-to-avoid-rental-scams-in-nairobi',
    title: 'How to Avoid Rental Scams in Nairobi',
    excerpt: 'Rental scams are unfortunately common in Kenya. Learn how to spot the red flags and protect yourself.',
    content: [
      { type: 'heading', level: 2, text: 'Common Rental Scams' },
      { type: 'paragraph', text: 'Every year, thousands of Kenyans lose money to rental scams. Fraudsters create fake listings and pose as landlords.' },
      { type: 'callout', tone: 'warning', text: 'Never send money for a rental property you haven\'t physically visited.' },
      { type: 'heading', level: 2, text: 'Steps to Protect Yourself' },
      { type: 'list', ordered: true, items: [
        'Always visit the property in person.',
        'Verify the landlord\'s identity with the title deed.',
        'Use HAMA\'s Verified Listings.',
        'Never pay without a signed tenancy agreement.',
        'Report suspicious listings to HAMA.',
      ] },
    ],
    coverImageUrl: 'hood-1-karen-houses.jpg',
    category: MOCK_BLOG_CATEGORIES[9],
    author: MOCK_BLOG_AUTHORS[0],
    tags: ['security', 'scams', 'renting'],
    status: 'published',
    publishedAt: '2026-08-05T10:00:00Z',
    featured: false,
    pinned: false,
    views: 2150,
    shares: 134,
    readingTime: 7,
    seoTitle: 'How to Avoid Rental Scams in Nairobi | HAMA',
    seoDescription: 'Learn how to identify and avoid common rental scams in Kenya.',
  },

  {
    id: 'post-3',
    slug: 'ultimate-moving-checklist-nairobi',
    title: 'The Ultimate Moving Checklist for Nairobi',
    excerpt: 'Moving to a new home in Nairobi? Use this comprehensive checklist to make sure nothing falls through the cracks.',
    content: [
      { type: 'heading', level: 2, text: '4 Weeks Before Moving' },
      { type: 'list', ordered: true, items: [
        'Research and book a reputable moving company.',
        'Notify your current landlord of your move-out date.',
        'Start decluttering — donate or sell items you no longer need.',
        'Update your address with banks, employers, and subscriptions.',
      ] },
      { type: 'heading', level: 2, text: '1 Week Before Moving' },
      { type: 'checklist', items: [
        'Pack non-essential items and label all boxes clearly.',
        'Confirm moving day logistics with your new landlord.',
        'Transfer or disconnect utilities at your current address.',
        'Clean the fridge and defrost the freezer.',
      ] },
      { type: 'callout', tone: 'tip', text: 'Take photos of your old apartment before leaving to protect your security deposit.' },
    ],
    coverImageUrl: 'guide-moving-checklist-desk.jpg',
    category: MOCK_BLOG_CATEGORIES[1],
    author: MOCK_BLOG_AUTHORS[1],
    tags: ['moving', 'checklist', 'relocation'],
    status: 'published',
    publishedAt: '2026-08-01T09:00:00Z',
    featured: true,
    pinned: false,
    views: 1890,
    shares: 203,
    readingTime: 6,
    seoTitle: 'Ultimate Moving Checklist for Nairobi | HAMA',
    seoDescription: 'A comprehensive moving checklist for anyone relocating within Nairobi.',
  },

  {
    id: 'post-4',
    slug: 'karen-neighbourhood-guide',
    title: 'Karen: A Complete Neighbourhood Guide',
    excerpt: 'Discover what makes Karen one of Nairobi\'s most desirable neighbourhoods. From schools to parks, here\'s everything you need to know.',
    content: [
      { type: 'heading', level: 2, text: 'Why Karen?' },
      { type: 'paragraph', text: 'Karen is synonymous with spacious living, lush greenery, and a tranquil suburban lifestyle within Nairobi.' },
      { type: 'heading', level: 2, text: 'Amenities & Lifestyle' },
      { type: 'list', ordered: false, items: [
        'Karen Country Club and Golf Course',
        'Karen Shopping Centre with cafes and boutiques',
        'Nairobi National Park is just minutes away',
        'Top international schools including Braeburn and German School',
      ] },
      { type: 'callout', tone: 'info', text: 'Average rent in Karen ranges from KSh 60,000 for a 2-bedroom apartment to KSh 250,000+ for a standalone house.' },
    ],
    coverImageUrl: 'hood-1-karen-houses.jpg',
    category: MOCK_BLOG_CATEGORIES[3],
    author: MOCK_BLOG_AUTHORS[1],
    tags: ['neighbourhoods', 'karen', 'nairobi'],
    status: 'published',
    publishedAt: '2026-07-28T08:00:00Z',
    featured: false,
    pinned: false,
    views: 4210,
    shares: 156,
    readingTime: 5,
    seoTitle: 'Karen Neighbourhood Guide | HAMA',
    seoDescription: 'Everything you need to know about living in Karen, Nairobi.',
  },

  {
    id: 'post-5',
    slug: 'home-decor-ideas-small-spaces',
    title: '10 Home Decor Ideas for Small Spaces',
    excerpt: 'Living in a compact apartment doesn\'t mean sacrificing style. Here are ten clever decor ideas that maximise space and look great.',
    content: [
      { type: 'heading', level: 2, text: 'Make Every Inch Count' },
      { type: 'paragraph', text: 'Small spaces demand creative thinking. The right furniture choices and layout can transform a cramped room into a cosy retreat.' },
      { type: 'heading', level: 2, text: 'Our Top 10 Picks' },
      { type: 'list', ordered: true, items: [
        'Use mirrors to create the illusion of more space.',
        'Invest in multi-functional furniture like storage ottomans.',
        'Go vertical with floating shelves.',
        'Choose light, neutral colours for walls.',
        'Use under-bed storage containers.',
        'Hang curtains higher to make ceilings look taller.',
        'Opt for a glass coffee table to keep sightlines open.',
        'Use corner shelves in awkward spaces.',
        'Declutter regularly — less is more.',
        'Add plants for life and colour without bulk.',
      ] },
      { type: 'callout', tone: 'tip', text: 'Check out the HAMA Marketplace for second-hand furniture deals in your area.' },
    ],
    coverImageUrl: 'service-cleaner.jpg',
    category: MOCK_BLOG_CATEGORIES[2],
    author: MOCK_BLOG_AUTHORS[0],
    tags: ['home-decor', 'interior-design', 'small-spaces'],
    status: 'published',
    publishedAt: '2026-07-25T07:30:00Z',
    featured: false,
    pinned: false,
    views: 3100,
    shares: 245,
    readingTime: 5,
    seoTitle: 'Home Decor Ideas for Small Spaces | HAMA',
    seoDescription: '10 clever home decor ideas for maximising small apartment spaces in Nairobi.',
  },

  {
    id: 'post-6',
    slug: 'understanding-your-tenancy-rights-kenya',
    title: 'Understanding Your Tenancy Rights in Kenya',
    excerpt: 'Know your rights as a tenant in Kenya. From rent increases to security deposits, this guide covers the legal basics.',
    content: [
      { type: 'heading', level: 2, text: 'The Landlord and Tenant Act' },
      { type: 'paragraph', text: 'Kenya\'s Landlord and Tenants (Shops, Hotels and Catering Establishments) Act governs most rental relationships. Understanding it is your first line of defence.' },
      { type: 'heading', level: 2, text: 'Key Rights Every Tenant Has' },
      { type: 'list', ordered: false, items: [
        'Right to a written tenancy agreement',
        'Right to habitable living conditions',
        'Protection against arbitrary eviction',
        'Right to receive a receipt for all payments',
        'Right to reasonable notice before rent increases',
      ] },
      { type: 'callout', tone: 'info', text: 'If your landlord refuses to make necessary repairs, you can file a complaint with the local municipal office or seek legal aid.' },
    ],
    coverImageUrl: 'hood-3-apartments-aerial.jpg',
    category: MOCK_BLOG_CATEGORIES[13],
    author: MOCK_BLOG_AUTHORS[0],
    tags: ['tenant-advice', 'legal', 'rights'],
    status: 'published',
    publishedAt: '2026-07-20T10:00:00Z',
    featured: false,
    pinned: false,
    views: 2670,
    shares: 178,
    readingTime: 7,
    seoTitle: 'Tenancy Rights in Kenya | HAMA',
    seoDescription: 'A comprehensive guide to understanding your rights as a tenant in Kenya.',
  },

  {
    id: 'post-7',
    slug: 'how-to-budget-for-your-first-apartment',
    title: 'How to Budget for Your First Apartment',
    excerpt: 'Moving into your first apartment is exciting — but costs can add up fast. Here\'s how to plan your budget wisely.',
    content: [
      { type: 'heading', level: 2, text: 'Upfront Costs' },
      { type: 'list', ordered: false, items: [
        'Security deposit (usually 1-3 months\' rent)',
        'First and last month\'s rent',
        'Moving expenses',
        'Basic furniture and appliances',
        'Utility connection fees',
      ] },
      { type: 'heading', level: 2, text: 'Monthly Ongoing Costs' },
      { type: 'list', ordered: false, items: [
        'Rent',
        'Electricity and water',
        'Internet',
        'Groceries',
        'Transportation',
      ] },
      { type: 'callout', tone: 'tip', text: 'Aim to spend no more than 30% of your monthly income on rent. Use the HAMA affordability calculator to find options within your budget.' },
    ],
    coverImageUrl: 'featured-2-dining-living.jpg',
    category: MOCK_BLOG_CATEGORIES[5],
    author: MOCK_BLOG_AUTHORS[1],
    tags: ['finance', 'budgeting', 'first-apartment'],
    status: 'published',
    publishedAt: '2026-07-15T08:00:00Z',
    featured: true,
    pinned: false,
    views: 5230,
    shares: 312,
    readingTime: 6,
    seoTitle: 'Budgeting for Your First Apartment | HAMA',
    seoDescription: 'Learn how to budget for your first apartment in Nairobi with this practical guide.',
  },

  {
    id: 'post-8',
    slug: 'best-home-service-providers-nairobi',
    title: 'How to Find the Best Home Service Providers in Nairobi',
    excerpt: 'Need an electrician, plumber, or cleaner? Here\'s how to find reliable home service providers in Nairobi.',
    content: [
      { type: 'heading', level: 2, text: 'Why Verified Service Providers Matter' },
      { type: 'paragraph', text: 'Hiring unverified tradespeople can lead to shoddy work, theft, or worse. Always use platforms that vet their providers.' },
      { type: 'heading', level: 2, text: 'Services You\'ll Likely Need' },
      { type: 'list', ordered: false, items: [
        'Plumbing repairs and installations',
        'Electrical work and wiring',
        'Deep cleaning and regular housekeeping',
        'Pest control',
        'Painting and wall repairs',
      ] },
      { type: 'callout', tone: 'tip', text: 'Browse verified service providers on the HAMA Services tab. Every provider is background-checked and reviewed by real tenants.' },
    ],
    coverImageUrl: 'service-electrician-1.jpg',
    category: MOCK_BLOG_CATEGORIES[6],
    author: MOCK_BLOG_AUTHORS[0],
    tags: ['services', 'home-maintenance', 'nairobi'],
    status: 'published',
    publishedAt: '2026-07-10T09:00:00Z',
    featured: false,
    pinned: false,
    views: 1980,
    shares: 92,
    readingTime: 4,
    seoTitle: 'Best Home Service Providers in Nairobi | HAMA',
    seoDescription: 'Find reliable, verified home service providers in Nairobi through HAMA.',
  },

  {
    id: 'post-9',
    slug: 'westlands-neighbourhood-guide',
    title: 'Westlands: The Urban Hub of Nairobi',
    excerpt: 'From nightlife to co-working spaces, Westlands has it all. Explore the neighbourhood that never sleeps.',
    content: [
      { type: 'heading', level: 2, text: 'The Westlands Vibe' },
      { type: 'paragraph', text: 'Westlands is Nairobi\'s entertainment and business hub. It blends high-rise living with a vibrant social scene.' },
      { type: 'heading', level: 2, text: 'Living in Westlands' },
      { type: 'list', ordered: false, items: [
        'Walkable distance to restaurants, bars, and cafes',
        'Close to major business districts',
        'Well-connected by public transport',
        'Modern apartment complexes with amenities',
      ] },
      { type: 'callout', tone: 'info', text: 'Rent for a 1-bedroom in Westlands typically ranges from KSh 35,000 to KSh 80,000 depending on the building and floor.' },
    ],
    coverImageUrl: 'hood-6-modern-highrise.jpg',
    category: MOCK_BLOG_CATEGORIES[3],
    author: MOCK_BLOG_AUTHORS[1],
    tags: ['neighbourhoods', 'westlands', 'nairobi'],
    status: 'published',
    publishedAt: '2026-07-05T08:00:00Z',
    featured: false,
    pinned: false,
    views: 3560,
    shares: 143,
    readingTime: 4,
    seoTitle: 'Westlands Neighbourhood Guide | HAMA',
    seoDescription: 'Discover what it\'s like to live in Westlands, Nairobi.',
  },

  {
    id: 'post-10',
    slug: 'hama-success-story-finding-my-dream-home',
    title: 'HAMA Success Story: How I Found My Dream Home in 2 Weeks',
    excerpt: 'Read how Grace found her perfect apartment in Kilimani using the HAMA app — and saved KSh 15,000 in the process.',
    content: [
      { type: 'heading', level: 2, text: 'Grace\'s Story' },
      { type: 'paragraph', text: 'After three months of fruitless house-hunting through agents and word-of-mouth, Grace decided to try HAMA. Within two weeks, she had signed a lease.' },
      { type: 'heading', level: 2, text: 'The Journey' },
      { type: 'list', ordered: true, items: [
        'Downloaded the HAMA app and set her budget at KSh 25,000.',
        'Filtered listings in Kilimani and Lavington.',
        'Visited three verified properties in one weekend.',
        'Chose a charming 1-bedroom with a balcony and signed the lease.',
      ] },
      { type: 'callout', tone: 'success', text: '"HAMA saved me so much time and stress. The verified listings gave me confidence, and I found a place I truly love." — Grace M.' },
    ],
    coverImageUrl: 'featured-1-modern-kitchen.jpg',
    category: MOCK_BLOG_CATEGORIES[8],
    author: MOCK_BLOG_AUTHORS[0],
    tags: ['success-stories', 'kilimani', 'renting'],
    status: 'published',
    publishedAt: '2026-06-28T08:00:00Z',
    featured: false,
    pinned: false,
    views: 1340,
    shares: 89,
    readingTime: 3,
    seoTitle: 'HAMA Success Story: Finding My Dream Home | HAMA',
    seoDescription: 'Read how Grace found her dream apartment in Kilimani using the HAMA app.',
  },
];
